import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav style={{ display: 'flex', gap: '1rem', padding: '1rem' }}>
          <a href="/">Home</a>
          <a href="/map">Map</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
